version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pw_social_media_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_media
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 