spring.application.name=pw-social-media
jwt.secret=your-very-very-very-very-very-very-very-very-very-very-very-long-secret
jwt.expiration=86400000

# MongoDB 配置
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=social_media

# 修改服务器端口为 8000
server.port=8000
